version: '3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: passwordless
      POSTGRES_USER: passwordless
      POSTGRES_PASSWORD: passwordless@nextjs
    volumes:
      - ./data:/var/lib/postgresql/data